services:
  weather.data_ingestion:
    container_name: weather.data_ingestion
    image: nhathuy16092003/weatherdataingestion
    build:
      context: ./weather_data_ingestion
      dockerfile: Dockerfile
    env_file:
      - ./weather_data_ingestion/.env
    depends_on:
      weather.databaseapi:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  weather.databaseapi:
    container_name: weather.databaseapi
    image: nhathuy16092003/weatherdatabaseapi
    build:
      context: ./weather_databaseapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./weather_databaseapi/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge